### PR TITLE
MultisigAddress implementation

### PR DESCRIPTION
**Pull request by syuan100**
- [x] Create MultisigAddress from multiple Address objects

### CODE REVIEW

**Comment by mfalkvidd** [comment]
Thanks for looking into multisig support!

Adding cross-reference to
https://github.com/helium/HIP/issues/157
and
https://github.com/helium/helium-wallet-rs/issues/221

**Comment by syuan100** [comment]
@mfalkvidd I also saw that basic multisig functions have already been implemented in helium-crypto-rs: https://github.com/helium/helium-crypto-rs/pull/21

Will be following this as a template

**Comment by syuan100** [comment]
Also, I raised this draft PR mostly for visibility so other people can jump on if necessary

**Comment by syuan100** [comment]
@mfalkvidd hello! I would like to have this reviewed for just the MultisigAddress implementation.

Another developer will be doing the rest of the multisig work. Thank you!

**Comment by syuan100** [comment]
Actually I just saw that there is a new "address" package. Should I move MultisigAddress into that package instead?

**Comment by syuan100** [comment]
Closing in favor of #290

**Pull request closed without merging**
