### PR TITLE
refactor(crypto): sha256, hash, and webpack

### LINKED ISSUE #95: Inaccurate encodings with Webpack.
I was having a weird issue with helium-js earlier this week. I was taking an account's bin and putting it to a b58 address. I realized that it didn't match my bin to b58 address using another library. Investigating further it seems that this is an issue caused by webpack and its handling of checksumBytes of bs58CheckEncode(). I encountered this issue while running a simple React app, using react-scripts.

### PR DESCRIPTION
**Pull request by vulet**
This resolved #95 for me.

### CODE REVIEW

**Comment by allenan** [comment]
hey @vulet thanks for looking into this. Was this just an issue with an intermediary state when deriving the b58 address from the public key? Just curious that we have existing tests around `bs58CheckEncode` that were passing before and continue to pass.

**Comment by allenan** [comment]
oh I see it's refactored to need fewer conversions to `'hex'`? I can still get your tests to pass with the old version by adding a `'hex'`, but I can see how it'd be better to have fewer places where that's needed. But I'm not sure exactly how that resolves the issue you mentioned in #95 where there was a webpack issue?

**Comment by vulet** [comment]
@allenan Thank you for the review, and I am sorry, I don't think I
explained my issue very well. My issue is encountered using Webpack/React,
so I am going to detail what has been happening to me while using
Webpack/React, as this doesn't seem to affect other Nodejs builds for me.
Locally, what is happening for me: the bs58CheckEncode's checksum is
currently being passed as a hex string. This is then used in checkSumBytes,
or checksumVerifyBytes in bs58ToBin(). This leads me to a checksumBytes or
checksumVerifyBytes of efbfbd06 for Bob, versus what I actually need, which
is c506d245 and obtainable by staying in buffer. I've got this working
locally, but this might be due to how I have set things up locally. I would
appreciate more time before being considered for merge as I'll be out for
the next couple of days and this PR might be too premature to throw into
master. Thanks, Michael.

**Comment by allenan** [comment]
@vulet no problem. Let's double check this when you get back. Just want to be extra cautious merging anything around the crypto libraries. Enjoy your travels!

**Comment by vulet** [comment]
Hi @allenan, thanks for waiting. This works for me, let me know if there's
anything that I can do to get this merged.

**Comment by allenan** [comment]
@vulet sorry for the delay. Hope you enjoyed your time in the mountains! I was able to reproduce this in a webpack environment, and verified that this fix works. Thanks for the fix 🙏

**Comment by vulet** [comment]
excellent @allenan, thanks for the merge!

**Pull request merged**
